apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv-ml
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/S/MLinfra/airflow_ml/logs
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: airflow-logs-pv-ml
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dvc-pv-ml
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/S/MLinfra/airflow_ml/dvc
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dvc-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: airflow-dvc-pv-ml
  storageClassName: ""